#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'basler','console_scripts','cam_top_pub'
__requires__ = 'basler'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('basler', 'console_scripts', 'cam_top_pub')()
    )
