#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'input-device','console_scripts','input_device_node'
__requires__ = 'input-device'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('input-device', 'console_scripts', 'input_device_node')()
    )
